[project]
name = "fuzzy"
version = "7.0.0"
description = "The iron-booted robotic resident of The Tsunami Zone."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hikari[speedups]==2.5.0",
    "hikari-crescent==1.4.0",
    "python-dotenv==1.2.1",
    "uvloop==0.22.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
